name: Danger

on: pull_request

jobs:
  is-pr-allowed-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Danger
        run: echo ${{ secrets.GITHUB_TOKEN }}
