name: Simple GitHub Action

on:
  push:
    branches:
      - testing

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log branch name
        run: echo ${GITHUB_REF#refs/heads/}
