name: Simple GitHub Action

on:
  pull_request:
    branches:
      - main

jobs:
  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Is allowed branch for master
        run: |
          BRANCH_NAME=$(echo ${{ github.head_ref }})
          echo $BRANCH_NAME
          if [[ $BRANCH_NAME =~ ^(develop|hotfix)\/ ]]; then
            echo "Branch name starts with supported prefix"
            exit
          else
            echo "Branch name doesn't start with supported prefix"
            exit 1 # Stop the action
          fi
