name: Is allowed branch for master?

on:
  push:
    branches-ignore:
      - develop
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Is allowed branch name
        run: |
          BRANCH_NAME=$(echo ${{ github.ref_name }})
          echo $BRANCH_NAME
          if [[ $BRANCH_NAME =~ ^(feature|hotfix|fix)\/ ]]; then
            echo "Branch name starts with supported prefix"
            exit 0
          else
            echo "Branch name doesn't start with supported prefix feature, hotfix or fix."
            exit 1 # Stop the action
          fi
