name: Simple GitHub Action

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Starting
        run: echo ${{github.ref}}
